"""Article Generator and Structured PDF: Crossref -> LM Studio -> Pydantic -> PDF."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import escape

import requests
from openai import OpenAI
from pydantic import BaseModel, Field, HttpUrl, ValidationError, field_validator
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer


class Source(BaseModel):
    authors: list[str] = Field(min_length=1)
    title: str = Field(min_length=3)
    year: int = Field(ge=1800, le=2100)
    url: HttpUrl
    doi: str | None = None


class ArticleSection(BaseModel):
    heading: str = Field(min_length=3, max_length=100)
    paragraphs: list[str] = Field(min_length=1, max_length=4)

    @field_validator("paragraphs")
    @classmethod
    def paragraphs_must_have_text(cls, value: list[str]) -> list[str]:
        if any(not paragraph.strip() for paragraph in value):
            raise ValueError("Paragraphs cannot be empty.")
        return value


class Report(BaseModel):
    title: str = Field(min_length=5, max_length=160)
    abstract: str = Field(min_length=40)
    introduction: list[str] = Field(min_length=1)
    sections: list[ArticleSection] = Field(min_length=2, max_length=5)
    conclusion: list[str] = Field(min_length=1)
    references: list[Source] = Field(min_length=2)


class ArticleContent(BaseModel):
    """The shorter structure generated by the model in grounded mode."""

    title: str = Field(min_length=5, max_length=160)
    abstract: str = Field(min_length=40, max_length=700)
    introduction: list[str] = Field(min_length=1, max_length=1)
    sections: list[ArticleSection] = Field(min_length=2, max_length=3)
    conclusion: list[str] = Field(min_length=1, max_length=1)


@dataclass
class SearchResult:
    source: Source
    abstract: str


def clean_html(value: str) -> str:
    return re.sub(r"<[^>]+>", "", value).replace("\n", " ").strip()


def first_text(value: object, fallback: str = "Unknown") -> str:
    if isinstance(value, list) and value:
        return str(value[0])
    return fallback


def search_crossref(topic: str, max_sources: int = 3) -> list[SearchResult]:
    """Search real scholarly metadata. Crossref returns the source URLs used later."""
    response = requests.get(
        "https://api.crossref.org/works",
        params={"query": topic, "rows": 8, "select": "title,author,published,URL,DOI,abstract"},
        headers={"User-Agent": "Article-Generator-Structured-PDF/1.0 (student project)"},
        timeout=30,
    )
    response.raise_for_status()
    items = response.json()["message"]["items"]
    results: list[SearchResult] = []
    for item in items:
        authors = [
            " ".join(part for part in (author.get("family"), author.get("given")) if part)
            for author in item.get("author", [])
        ]
        date_parts = item.get("published", {}).get("date-parts", [[0]])
        year = date_parts[0][0] if date_parts and date_parts[0] else 0
        if not authors or not year or not item.get("title") or not item.get("URL"):
            continue
        results.append(SearchResult(
            source=Source(
                authors=authors,
                title=first_text(item["title"]),
                year=year,
                url=item["URL"],
                doi=item.get("DOI"),
            ),
            abstract=clean_html(item.get("abstract", "No abstract available.")),
        ))
        if len(results) == max_sources:
            break
    if len(results) < 2:
        raise RuntimeError("Crossref returned too few usable sources. Try a more specific topic.")
    return results


def source_payload(results: list[SearchResult]) -> str:
    return json.dumps([{
        "authors": result.source.authors[:3],
        "title": result.source.title,
        "year": result.source.year,
        "abstract": result.abstract[:500],
    } for result in results], ensure_ascii=False, indent=2)


def get_report(topic: str, sources: list[SearchResult], model: str, base_url: str,
               without_search: bool) -> Report:
    context = "No source material is available." if without_search else source_payload(sources)
    system = """You write short technical or scientific articles. Return only valid JSON, never Markdown.
Use the exact report structure requested. Use APA-style in-text citations such as (Surname, 2024).
If sources are provided, cite ONLY those sources. Do not invent statistics or claims.
Write concise Finnish. Do not explain your reasoning. /no_think"""
    output_model: type[BaseModel] = Report if without_search else ArticleContent
    schema = output_model.model_json_schema()
    reference_instruction = (
        "Include exactly two best-effort references for later manual verification."
        if without_search
        else "Do not include a references field; the application adds verified references."
    )
    user = f"""Write a 300-400 word article about: {topic}. /no_think

Use one abstract paragraph, one introduction paragraph, two main sections with one paragraph each,
and one conclusion paragraph. {reference_instruction}

<sources>
{context}
</sources>

Return a JSON object conforming to this JSON Schema:
{json.dumps(schema, ensure_ascii=False)}"""
    client = OpenAI(base_url=base_url, api_key="lm-studio", timeout=1800.0, max_retries=0)
    print("LM Studio is generating the structured article...")
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
        response_format={
            "type": "json_schema",
            "json_schema": {
                "name": "article_report",
                "strict": True,
                "schema": schema,
            },
        },
        temperature=0.2,
        max_tokens=2200,
    )
    if response.choices[0].finish_reason == "length":
        raise RuntimeError("LM Studio stopped at the token limit before the JSON was complete.")
    message = response.choices[0].message
    # Some Qwen models served by LM Studio place JSON in reasoning_content.
    content = message.content or getattr(message, "reasoning_content", None)
    if not content:
        raise RuntimeError("LM Studio returned an empty response.")
    try:
        generated = output_model.model_validate_json(content)
    except ValidationError as exc:
        raise RuntimeError(f"Model output failed Pydantic validation:\n{exc}") from exc

    if without_search:
        return Report.model_validate(generated.model_dump())

    article = ArticleContent.model_validate(generated.model_dump())
    return Report(
        title=article.title,
        abstract=article.abstract,
        introduction=article.introduction,
        sections=article.sections,
        conclusion=article.conclusion,
        references=[result.source for result in sources],
    )


def safe_filename(topic: str) -> str:
    """Keep the topic readable while removing characters forbidden by Windows."""
    name = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", topic)
    name = re.sub(r"\s+", " ", name).strip(" .")
    return (name or "article")[:120]


def apa(reference: Source) -> str:
    authors = ", ".join(reference.authors)
    doi_or_url = f"https://doi.org/{reference.doi}" if reference.doi else str(reference.url)
    return f"{authors}. ({reference.year}). {reference.title}. {doi_or_url}"


def make_pdf(report: Report, output: Path) -> None:
    styles = getSampleStyleSheet()
    title = ParagraphStyle("ArticleTitle", parent=styles["Title"], alignment=TA_CENTER, fontSize=18, leading=22, spaceAfter=10)
    heading = ParagraphStyle("ArticleHeading", parent=styles["Heading2"], spaceBefore=12, spaceAfter=6)
    body = ParagraphStyle("ArticleBody", parent=styles["BodyText"], fontSize=10.5, leading=14, spaceAfter=7)
    abstract = ParagraphStyle("Abstract", parent=body, leftIndent=8*mm, rightIndent=8*mm, backColor=colors.whitesmoke, borderPadding=6)
    document = SimpleDocTemplate(str(output), pagesize=A4, rightMargin=20*mm, leftMargin=20*mm, topMargin=18*mm, bottomMargin=18*mm, title=report.title, author="Generated with LM Studio")
    story = [Paragraph(escape(report.title), title), Paragraph("<b>Tiivistelmä</b><br/>" + escape(report.abstract), abstract), Spacer(1, 5)]
    story.append(Paragraph("Johdanto", heading))
    story.extend(Paragraph(escape(p), body) for p in report.introduction)
    for section in report.sections:
        story.append(Paragraph(escape(section.heading), heading))
        story.extend(Paragraph(escape(p), body) for p in section.paragraphs)
    story.append(Paragraph("Johtopäätökset", heading))
    story.extend(Paragraph(escape(p), body) for p in report.conclusion)
    story.append(PageBreak())
    story.append(Paragraph("Lähteet", heading))
    story.extend(Paragraph(escape(apa(reference)), body) for reference in report.references)
    document.build(story)


def main() -> None:
    parser = argparse.ArgumentParser(description="Article Generator and Structured PDF")
    parser.add_argument("--topic", required=True)
    parser.add_argument("--model", default="qwen/qwen3.8-27b")
    parser.add_argument("--base-url", default="http://localhost:1234/v1")
    parser.add_argument("--output-dir", default="output")
    parser.add_argument("--without-search", action="store_true", help="Comparison mode: skip Crossref search.")
    args = parser.parse_args()
    print(f"Topic: {args.topic}")
    if not args.without_search:
        print("Searching Crossref for verified sources...")
    sources = [] if args.without_search else search_crossref(args.topic)
    if sources:
        print(f"Found {len(sources)} verified sources.")
    report = get_report(args.topic, sources, args.model, args.base_url, args.without_search)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    file_stem = safe_filename(args.topic)
    if args.without_search:
        file_stem += " - ilman verkkohakua"
    json_path = output_dir / f"{file_stem}.json"
    pdf_path = output_dir / f"{file_stem}.pdf"
    json_path.write_text(report.model_dump_json(indent=2), encoding="utf-8")
    make_pdf(report, pdf_path)
    print(f"Validated JSON saved: {json_path}")
    print(f"PDF saved: {pdf_path}")


if __name__ == "__main__":
    main()
